export const SUBSCRIPTION_PLANS = {
  FREE: 'Free',
  BASIC: 'Basic',
  PREMIUM: 'Premium'
} as const

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
} as const

export const NOTIFICATION_TYPES = {
  SUBSCRIPTION_EXPIRY_WARNING: 'SUBSCRIPTION_EXPIRY_WARNING',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  DEVICE_LIMIT_EXCEEDED: 'DEVICE_LIMIT_EXCEEDED'
} as const

export const TELEBIRR_CONSTANTS = {
  TIMEOUT_EXPRESS: '30m',
  CURRENCY: 'ETB',
  TRADE_STATUS: {
    SUCCESS: 'TRADE_SUCCESS',
    FAILED: 'TRADE_FAILED',
    CLOSED: 'TRADE_CLOSED'
  }
} as const

export const EXPIRY_WARNING_DAYS = 3

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100
} as const